version: '3.8'

services:
  # Kong Database (PostgreSQL)
  kong-database:
    image: postgres:15-alpine
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong_password
    ports:
      - "5433:5432"
    volumes:
      - kong-db-data:/var/lib/postgresql/data
    networks:
      - fullstack-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Kong Database Migration
  kong-migration:
    image: kong:3.4
    container_name: kong-migration
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PORT: 5432
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong_password
      KONG_PG_DATABASE: kong
    networks:
      - fullstack-network
    depends_on:
      kong-database:
        condition: service_healthy
    restart: on-failure

  # Kong Gateway
  kong:
    image: kong:3.4
    container_name: kong-gateway
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PORT: 5432
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong_password
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      # Enable plugins
      KONG_PLUGINS: bundled,jwt,acl,rate-limiting,cors,request-transformer,response-transformer
    ports:
      - "8000:8000"  # Proxy HTTP
      - "8443:8443"  # Proxy HTTPS
      - "8001:8001"  # Admin API HTTP
      - "8444:8444"  # Admin API HTTPS
    networks:
      - fullstack-network
    depends_on:
      kong-database:
        condition: service_healthy
      kong-migration:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Konga (Kong Admin UI)
  konga:
    image: pantsel/konga:latest
    container_name: konga
    environment:
      NODE_ENV: development
      # Use SQLite instead of PostgreSQL for Konga (compatibility fix)
      # DB_ADAPTER: postgres
      # DB_HOST: kong-database
      # DB_PORT: 5432
      # DB_USER: kong
      # DB_PASSWORD: kong_password
      # DB_DATABASE: konga
      TOKEN_SECRET: some-secret-token
    ports:
      - "1337:1337"
    volumes:
      - konga-data:/app/kongadata
    networks:
      - fullstack-network
    depends_on:
      kong:
        condition: service_healthy
    restart: unless-stopped

networks:
  fullstack-network:
    external: true
    name: fullstack-project-hybrid-network

volumes:
  kong-db-data:
    driver: local
  konga-data:
    driver: local
