version: '3.8'

# 🚀 LIGHTWEIGHT LOGGING STACK (Loki + Grafana + Promtail)
# Resource Usage: ~300-400MB RAM
# Best for: Local development, quick log searches
# Uses your existing Grafana instance!

services:
  # Loki - Log Aggregation Storage (Lightweight alternative to Elasticsearch)
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3200:3100"  # Changed from 3100 to avoid Grafana conflict
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/loki
    networks:
      - fullstack-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Promtail - Log Collector (Lightweight alternative to Filebeat)
  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - promtail-config:/etc/promtail
    command: 
      - '-config.file=/etc/promtail/config.yml'
      - '-config.expand-env=true'
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    networks:
      - fullstack-network
    depends_on:
      - loki
    restart: unless-stopped

networks:
  fullstack-network:
    external: true
    name: fullstack-project-hybrid-network

volumes:
  loki-data:
    driver: local
  promtail-config:
    driver: local
