# Prometheus Configuration for Kong Gateway Monitoring

global:
  scrape_interval: 15s      # Scrape metrics every 15 seconds
  evaluation_interval: 15s  # Evaluate rules every 15 seconds
  external_labels:
    cluster: 'local-development'
    environment: 'development'

# Alertmanager configuration (optional - can be added later)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Kong Gateway Metrics
  - job_name: 'kong'
    static_configs:
      - targets: ['kong-gateway:8001']
        labels:
          service: 'kong-gateway'
          component: 'api-gateway'
    metrics_path: '/metrics'
    scrape_interval: 10s  # Scrape Kong more frequently

  # PostgreSQL Exporter (if you add postgres_exporter later)
  # - job_name: 'kong-database'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']
  #       labels:
  #         service: 'kong-database'

  # Node Exporter for host metrics (if you add it later)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  #       labels:
  #         service: 'node-exporter'

  # Microservices metrics (if they expose Prometheus endpoints)
  # Auth Service
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']
        labels:
          service: 'auth-service'
          component: 'microservice'
    metrics_path: '/metrics'
    scrape_interval: 15s

  # User Service
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3003']
        labels:
          service: 'user-service'
          component: 'microservice'
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Carrier Service
  - job_name: 'carrier-service'
    static_configs:
      - targets: ['carrier-service:3004']
        labels:
          service: 'carrier-service'
          component: 'microservice'
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Customer Service
  - job_name: 'customer-service'
    static_configs:
      - targets: ['customer-service:3005']
        labels:
          service: 'customer-service'
          component: 'microservice'
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Pricing Service
  - job_name: 'pricing-service'
    static_configs:
      - targets: ['pricing-service:3006']
        labels:
          service: 'pricing-service'
          component: 'microservice'
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Translation Service
  - job_name: 'translation-service'
    static_configs:
      - targets: ['translation-service:3007']
        labels:
          service: 'translation-service'
          component: 'microservice'
    metrics_path: '/metrics'
    scrape_interval: 15s
