apiVersion: 1

datasources:
  # Loki - Log Aggregation
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: Loki
          matcherRegex: "correlationId[\":]\\s*\"([^\"]+)\""
          name: CorrelationID
          url: $${__value.raw}
    editable: true

  # Prometheus - Metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
    editable: true
