apiVersion: 1

datasources:
  # Loki for log aggregation
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: loki
          matcherRegex: "correlationId\":\"([^\"]+)"
          name: CorrelationID
          url: $${__value.raw}
    editable: true

  # Prometheus for metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    jsonData:
      timeInterval: 5s
    editable: true
