version: '3.8'

services:
  # User Service Application (using shared database)
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: southern-martin-user-service
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-3003}
      # Shared Database Configuration (same as Auth Service)
      DB_HOST: shared-user-db
      DB_PORT: 3306
      DB_USERNAME: shared_user
      DB_PASSWORD: shared_password_2024
      DB_DATABASE: shared_user_db
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
      
      # Shared Redis Configuration
      REDIS_HOST: shared-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: shared_redis_password_2024
      REDIS_KEY_PREFIX: user
    ports:
      - "${PORT:-3003}:3003"
    depends_on:
      shared-user-db:
        condition: service_healthy
      shared-redis:
        condition: service_healthy
    networks:
      - shared-services-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3003/api/v1/health"]
      timeout: 10s
      retries: 3
      interval: 30s
      start_period: 40s

  # Note: Using shared database (shared_user_db) and shared Redis
  # This service shares the same database as the Auth Service
  # See ../shared-database/ and ../shared-redis/ for configuration

networks:
  shared-services-network:
    external: true
    name: southern-martin-shared-services-network

