server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Scrape Docker container logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Extract container name
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container_name'
      
      # Extract container ID
      - source_labels: ['__meta_docker_container_id']
        target_label: 'container_id'
      
      # Extract service name from container labels
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      
      # Extract project name
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'project'
      
      # Add log level extraction from message
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'

    # Pipeline stages for parsing structured logs
    pipeline_stages:
      # Parse JSON logs from NestJS services
      - json:
          expressions:
            level: level
            message: message
            timestamp: timestamp
            context: context
            trace: trace
            userId: userId
            requestId: requestId
      
      # Extract log level if present
      - labels:
          level:
          context:
          service:
      
      # Parse timestamp
      - timestamp:
          source: timestamp
          format: RFC3339
      
      # Output formatting
      - output:
          source: message

  # Specific configs for services
  - job_name: kong
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: ['kong-gateway']
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
      - replacement: 'kong'
        target_label: 'service'

  - job_name: auth-service
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: ['auth-service']
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
      - replacement: 'auth-service'
        target_label: 'service'
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: message
            time: timestamp
      - labels:
          level:

  - job_name: user-service
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: ['user-service']
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
      - replacement: 'user-service'
        target_label: 'service'
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: message

  - job_name: databases
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: ['shared_user_db', 'kong-database', 'shared-redis']
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
      - source_labels: ['__meta_docker_container_name']
        target_label: 'service'
